# Generated by Django 3.2.5 on 2022-02-20 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ContactusForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255)),
                ('subject', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Employment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fitst_lastname', models.CharField(max_length=255, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(max_length=500, verbose_name='شماره تماس')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('father_name', models.CharField(max_length=255, verbose_name='نام پدر')),
                ('Dateofbirth', models.CharField(max_length=300, verbose_name='تاریخ تولد')),
                ('placeofbirth', models.CharField(max_length=255, verbose_name='محل تولد')),
                ('national_code', models.CharField(max_length=500, verbose_name='کد ملی')),
                ('number_Birth_certificate', models.CharField(max_length=500, verbose_name='شماره شناسنامه')),
                ('Maritalstatus_numberofchildren', models.CharField(max_length=255, verbose_name='وضعیت تاهل و تعداد فرزند')),
                ('militaryservicestatus', models.CharField(max_length=255, verbose_name='وضعیت نظام وظیفه')),
                ('field_study_location', models.CharField(max_length=255, verbose_name='رشته تحصیلی و محل آن')),
                ('Last_educational_certificate', models.CharField(max_length=255, verbose_name='آخرین مدرک تحصیلی')),
                ('salon', models.CharField(blank=True, choices=[('sandogh', 'صندوق'), ('mizbani', 'میزبانی'), ('hesabdari', 'حسابداری')], max_length=20, verbose_name='سالن')),
                ('peyk', models.CharField(blank=True, choices=[('edari', 'اداری'), ('komakashpaz', 'کمک آشپز'), ('sobhane', 'صبحانه')], max_length=20, verbose_name='پیک')),
                ('ashpaz', models.CharField(blank=True, choices=[('khadamat', 'خدمات'), ('amadesazi', 'آماده سازی')], max_length=20, verbose_name='آشپز')),
                ('Chef_assistantchef', models.CharField(blank=True, choices=[('takhtekar', 'تخته کار'), ('amadesazi', 'آماده سازی'), ('ghasabi', 'قصابی'), ('ashpaziirani', 'آشپزی ایرانی'), ('ashpazifarangi', 'آشپزی فرنگی')], max_length=20, verbose_name='دستیار آشپز')),
                ('work_name1', models.CharField(blank=True, max_length=255, verbose_name='نام محل کار ۱')),
                ('work_time1', models.CharField(blank=True, max_length=255, verbose_name='مدت زمان سابقه کار ۱')),
                ('last_rights1', models.CharField(blank=True, max_length=255, verbose_name='آخرین حقوق کار ۱')),
                ('Reason_for_leaving_work1', models.CharField(blank=True, max_length=255, verbose_name='دلیل ترک کار ۱')),
                ('Manager_name1', models.CharField(blank=True, max_length=255, verbose_name='مدیر کار ۱')),
                ('work_name2', models.CharField(blank=True, max_length=255, verbose_name='نام محل کار ۲')),
                ('work_time2', models.CharField(blank=True, max_length=255, verbose_name='مدت زمان سابقه کار ۲')),
                ('last_rights2', models.CharField(blank=True, max_length=255, verbose_name='آخرین حقوق کار ۲')),
                ('Reason_for_leaving_work2', models.CharField(blank=True, max_length=255, verbose_name='دلیل ترک کار ۲')),
                ('Manager_name2', models.CharField(blank=True, max_length=255, verbose_name='مدیر کار ۲')),
                ('work_name3', models.CharField(blank=True, max_length=255, verbose_name='نام محل کار ۳')),
                ('work_time3', models.CharField(blank=True, max_length=255, verbose_name='مدت زمان سابقه کار ۳')),
                ('last_rights3', models.CharField(blank=True, max_length=255, verbose_name='آخرین حقوق کار ۳')),
                ('Reason_for_leaving_work3', models.CharField(blank=True, max_length=255, verbose_name='دلیل ترک کار ۳')),
                ('Manager_name3', models.CharField(blank=True, max_length=255, verbose_name='مدیر کار ۳')),
                ('Motivation_to_collaborate', models.TextField(verbose_name='انگیزه همکاری بارستوران فرشاد')),
                ('english_language', models.CharField(blank=True, choices=[('awli', 'عالی'), ('khob', 'خوب'), ('motevaset', 'متوسط'), ('zaief', 'ضعیف')], max_length=20, verbose_name='مهارت زبان انگلیسی')),
                ('word', models.CharField(blank=True, choices=[('awli', 'عالی'), ('khob', 'خوب'), ('motevaset', 'متوسط'), ('zaief', 'ضعیف')], max_length=20, verbose_name='تسلط به word')),
                ('exel', models.CharField(blank=True, choices=[('awli', 'عالی'), ('khob', 'خوب'), ('motevaset', 'متوسط'), ('zaief', 'ضعیف')], max_length=20, verbose_name='تسلط به exel')),
                ('other_skills', models.CharField(blank=True, max_length=255, verbose_name='سایر مهارت ها یا زبان خارجی')),
                ('bime_time', models.CharField(max_length=255, verbose_name='آیا سابقه بیمه دارید؟ و مدت زمان آن؟')),
                ('salary', models.CharField(max_length=255, verbose_name='میزان حقوق درخواستی (به تومان)')),
                ('min_time_coperation', models.CharField(max_length=255, verbose_name='حداقل زمان همکاری')),
                ('work_per_day', models.CharField(max_length=255, verbose_name='توانایی چند ساعت کار در روز را دارید؟')),
                ('smoke', models.CharField(choices=[('bale', 'بله'), ('kheyr', 'خیر')], max_length=20, verbose_name='آیا دخانیات مصرف میکنید؟')),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='section1/%Y/%m/%d/')),
                ('title', models.TextField(max_length=800)),
                ('param', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=800)),
                ('param', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='section3/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='HomeSection4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='section4/%Y/%m/%d/')),
                ('title', models.TextField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=0, max_digits=10)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.category')),
            ],
            options={
                'ordering': ('name',),
                'index_together': {('id', 'slug')},
            },
        ),
    ]
